version: '3.7'

services:
  django:
    container_name: ${PROJECT_NAME}_django
    hostname: ${PROJECT_NAME}_django
    restart: always
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    command: bash /${PROJECT_NAME}/run_django.sh
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEPLOY_ENVIRONMENT: ${DEPLOY_ENVIRONMENT}
      NGINX_EXTERNAL_PORT: ${NGINX_EXTERNAL_PORT}
    volumes:
      - vo_static:/static:cached
      - vo_media:/media:cached
    ports:
      - "8000"
      - "${DJANGO_DEBUG_PORT}:${DJANGO_DEBUG_PORT}"
    links:
      - postgres
    depends_on:
      - postgres

  nextjs:
    container_name: ${PROJECT_NAME}_nextjs
    restart: always
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - fte_release:/${PROJECT_NAME}/dist:cached
    working_dir: /${PROJECT_NAME}

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    build:
      context: ./docker/nginx/
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      NGINX_EXTERNAL_PORT: ${NGINX_EXTERNAL_PORT}
    depends_on:
      - django
      - nextjs
    links:
      - django
      - nextjs
    volumes:
      - vo_static:/www/static:cached
      - vo_media:/www/media:cached
      - fte_release:/${PROJECT_NAME}/dist:cached
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

  postgres:
    container_name: ${PROJECT_NAME}_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PROJECT_NAME: ${PROJECT_NAME}
    build: docker/postgres
    command: postgres -c config_file=/etc/postgres.conf
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: "2"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  vo_static:
    driver: local
  vo_media:
    driver: local
  postgres_db:
  fte_release:
