# Generated by Django 5.0.1 on 2024-01-20 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Nombre del producto', max_length=32, unique=True, verbose_name='Nombre del producto')),
                ('price', models.FloatField(default=0.0, verbose_name='Precio del producto')),
                ('unit_price', models.FloatField(default=0.0, verbose_name='Precio del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
