# Generated by Django 5.0.1 on 2024-01-21 00:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchScraping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('search_json', models.JSONField(blank=True, default=dict, verbose_name='JSON de del scrapper de la busqueda')),
                ('text', models.TextField(blank=True, default='', help_text='Texto de busqueda', max_length=256, verbose_name='Texto de busqueda')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_scraping', to='core.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Search Scraping',
                'verbose_name_plural': 'Searchs Scraping',
            },
        ),
    ]
